Image upload
PlatziDev/pulse pull request #18
Opened 2017-11-16 10:43 UTC by demian-arenas

Now, **Pulse** can upload an image with only Drop a local image onto the editor, this image upload to Imgur and automatically sets the image in the Markdown file. 

If the file who drops onto editor isn't supported by Imgur, it inserts schema of an image but with message 'Problem with the format file'. like this  `![Problem with the format file](url)`

2017-11-16 18:07 UTC, sergiodxa requested changes
You also created a branch from the branch you used to your other PR so you send the whole code of that PR here.

2017-11-16 18:07 UTC, sergiodxa commented on renderer/pages/index.js
> +  handleDrop = e => imageDrop(e, this)
Don't do this, be explicit, `e` could be `event` or `error` or whatever.

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +let validateFile = (file) => {
Use const, only use let if you realize you need to change this variable later (tip: never do it, use immutable code)

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +  let imageFormat = ['jpeg', 'png', 'gif', 'peg', 'apng', 'tiff', 'pdf', 'xcf']
Use const, only use let if you realize you need to change this variable later (tip: never do it, use immutable code)

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +    let res = new RegExp("\\b(" + kind + ")\\b")
Use const, only use let if you realize you need to change this variable later (tip: never do it, use immutable code)

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +  let fd = new FormData()
Use const, only use let if you realize you need to change this variable later (tip: never do it, use immutable code)

Be explicit, use formData not fd, fd doesn't say anything about what's inside

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +let sendData = (_this, file) => {
Use const, only use let if you realize you need to change this variable later (tip: never do it, use immutable code)

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +  let xhttp = new XMLHttpRequest()
Use const, only use let if you realize you need to change this variable later (tip: never do it, use immutable code)

Use Fetch API not XMLHttpRequest

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +let imageDrop = (e, _this) => {
Use const, only use let if you realize you need to change this variable later (tip: never do it, use immutable code)

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +  e.preventDefault()
Be explicit, use `event` not `e`, it doesn't say anything about what is inside

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +  let event = {}
Use const, only use let if you realize you need to change this variable later (tip: never do it, use immutable code)

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +  let valido = validateFile(file)
Use const, only use let if you realize you need to change this variable later (tip: never do it, use immutable code)

Code in english

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +  let file = e.dataTransfer.files[0]
Use const, only use let if you realize you need to change this variable later (tip: never do it, use immutable code)

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +  } else {
Don't use `else`, just `return` inside the `if`

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +    event.target = {
Avoid mutations

2017-11-16 18:07 UTC, sergiodxa commented on renderer/components/image-drop.js
> +//  validate file format with a list of format supports imgur
This whole file is not a component, is a lib, move it to another directory.

2017-11-16 18:07 UTC, sergiodxa commented on renderer/pages/index.js
> +import imageDrop from '../components/image-drop'
Aside of that file not being a component it's only used inside this page so it doesn't need to be externalized

2017-11-18 03:09 UTC, demian-arenas commented
Sergio, I have a doubt. 
I also want to contribute to the issue of 'Dark Mode' and 'Pulse Protocol'. I send that enhancement at once in this PR or in another?

2017-11-18 03:35 UTC, sergiodxa requested changes

2017-11-18 03:35 UTC, sergiodxa commented on renderer/pages/index.js
> +      .then(response => response.json())
Use Async/Await

2017-11-18 03:35 UTC, sergiodxa commented
@demian-arenas each feature should be a PR

2026-06-26 20:45 UTC, closed without merging